### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://kodi.weblate.cloud/projects/kodi-add-ons-scripts/script-embuary-info/) for Kodi add-ons: scripts/script.embuary.info.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by gade01 — APPROVED** [review]
Looking good to me.

**Comment by roidy** [comment]
Hi Sualfred, 

Sorry to bother you but I don't want to push any updates to script.embuary.info until I know exactly what is going on with the recent Weblate translations. Twelve days ago you merged this pull request containing new translations however they all seem to be in the wrong location, they have been merged into the root directory and not the resource/language directory.

Please advise what to do about this.

Thanks
roidy

**Comment by gade01** [comment]
@roidy @sualfred 
Oh wow, that looks like a mess.
I'll investigate how that happened and what went wrong at Weblate.
I'll probably do a PR to fix this.

**Comment by roidy** [comment]
@gade01 👍 Thanks

**Pull request merged**
