### PR TITLE
fix skins default

### PR DESCRIPTION
**Pull request by caperucitaferoz**
- fix title font to 'font_MainMenu'
- move icon tmdb
- add duration
- format plot

Before:
Captura1

After:
Captura4

### CODE REVIEW

**Comment by sualfred** [comment]
@caperucitaferoz 
I cannot reproduce this issue on my end.

**Comment by caperucitaferoz** [comment]
have you tried the confluence and estuary skins?

**Comment by sualfred** [comment]
Tried Estuary, no problem at all (Matrix)

Edit:
Another member tested it and cannot confirm this issue too

**Comment by caperucitaferoz** [comment]
My tests are on windows.
Attached some images ...

Your version in the skin confluence:
confluence

Your version in the skin estuary:
embuary

My proposal in both sinks:
embuary2

Look at the title size, the location and size of the logo and the new duration field.

**Comment by sualfred** [comment]
Ah. Confluence. So it's a Confluence bug. The script ships a default skin for Estuary. If a skin is not providing the Estuary default fonts or overwrites other things, it has to create a own shipped windows. That's nothing I can or will ever take care of. 

If u r using Confluence, I suggest you to create a copy of the Embuary Info windows and place it into the Confluence folder. By this u can change windows to fit your own needs.  Kodi is alway choosing the windows of the active skin. If there is none, it falls back to the addon provided one.

**Comment by caperucitaferoz** [comment]
Sorry, I can't quite understand your reasons for closing this proposal without accepting it. I think it brings something new to your script (movie duration times) and fixes a bug when viewed with one of the official kodi skins. All this without affecting the operation in other skins.
However, it is your script and I respect your decision.

**Comment by sualfred** [comment]
Because it's not a bug of the script, it's a bug of Confluence.

In skins you have to provide the font set of the default Kodi skin to keep compatiblity, which Confluence did not correctly. 
The downside of scripts, which are providing own windows, is always that u have zero control about the things the loaded skin does. You cannot use any availabe fancy own skinning engine features or what so ever.  

Regarding the other format issues, there must be something set in Confluence which ignores the left/right thing. Using left/right is the correct approach nowadays. Kodi is not really responsive in multi resolutions, but this is the only option to achieve something similar.

Again, thx for the input, but if a skin displays a script window wrong, the skin has to provide a own skinned theme window for it. The skin is causing the bug because it is not using the defaults, so it has to be fixed there and not in the script.

**Pull request closed without merging**
